

services:
  otm-docker:
    shm_size: 1g
    restart: always
    image: otm-meins
    container_name: otm-meins
    environment:
      - LETSENCRYPT=0
      - EMAIL=admin@this.srv
      - DOMAIN=otm.weier2000.de
      - WHITELIST=127.0.0.1
      - MOD_TILE_PREVENT_EXPIRATION=1
    volumes:
      - ./data:/mnt
      - ./data/db:/var/lib/postgresql
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - '8880:80'
      - '88443:443'
